"""empty message

Revision ID: 2e2b657b34a1
Revises: 8e6d78300de8
Create Date: 2019-01-26 12:14:25.992728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2b657b34a1'
down_revision = '8e6d78300de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_activity', sa.Column('item_identifier', sa.String(length=32), nullable=True))
    op.drop_column('user_activity', 'item_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_activity', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_activity', 'item_identifier')
    # ### end Alembic commands ###
