"""empty message

Revision ID: 8e6d78300de8
Revises: ff80279a8210
Create Date: 2019-01-26 10:54:26.967288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6d78300de8'
down_revision = 'ff80279a8210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_activity', sa.Column('change_type', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_activity', 'change_type')
    # ### end Alembic commands ###
